merge branch into trunk after a long day of hard work...
git-svn-id: https://simspark.svn.sourceforge.net/svnroot/simspark@176 b11e7cac-9b9e-4fc5-a478-b6e702e8797b

diff --git a/trunk/rcssserver3d/rcssserver3d/rcsoccersim3d.in b/trunk/rcssserver3d/rcssserver3d/rcsoccersim3d.in
--- a/trunk/rcssserver3d/rcssserver3d/rcsoccersim3d.in
+++ b/trunk/rcssserver3d/rcssserver3d/rcsoccersim3d.in
@@ -31,6 +31,13 @@ if [ ! -f $MON ]; then
     exit 1
 fi
 
+AGT="$bindir/rcssagent3d"
+if [ ! -f $AGT ]; then
+    echo "Error: $AGT does not exist!"
+    echo ""
+    exit 1
+fi
+
 #--------------------------------------------------
 # set handler
 #
